### ISSUE TITLE
Not working after today's update

### ISSUE THREAD

**Issue by orange2008** [lukeorth/poison#115]
Hello, my Hugo website suddenly stopped building after I updated it to the latest version.

HOWTO:
Just create a new Hugo website and enable the theme, then use `hugo server` to start the server

Error log:
```
╭─frank@frank-confidential ~/Documents/frankruan ‹master●› 
╰─$ hugo  server
Start building sites … 
hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1
ERROR 2023/07/11 22:07:32 render of "taxonomy" failed: execute of template failed: template: _default/list.html:1:3: executing "_default/list.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:16:7: executing "partials/head/head.html" at <partial "head/meta.html" .>: error calling partial: "/home/frank/Documents/frankruan/themes/poison/layouts/partials/head/meta.html:27:26": execute of template failed: template: partials/head/meta.html:27:26: executing "partials/head/meta.html" at <.Resources.Get>: can't evaluate field Get in type resource.Resources
ERROR 2023/07/11 22:07:32 render of "taxonomy" failed: execute of template failed: template: _default/list.html:1:3: executing "_default/list.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:16:7: executing "partials/head/head.html" at <partial "head/meta.html" .>: error calling partial: "/home/frank/Documents/frankruan/themes/poison/layouts/partials/head/meta.html:27:26": execute of template failed: template: partials/head/meta.html:27:26: executing "partials/head/meta.html" at <.Resources.Get>: can't evaluate field Get in type resource.Resources
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:1:3: executing "index.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:16:7: executing "partials/head/head.html" at <partial "head/meta.html" .>: error calling partial: "/home/frank/Documents/frankruan/themes/poison/layouts/partials/head/meta.html:27:26": execute of template failed: template: partials/head/meta.html:27:26: executing "partials/head/meta.html" at <.Resources.Get>: can't evaluate field Get in type resource.Resources
Built in 48 ms
```

**Comment by lukeorth** [comment]
It seems this issue was caused when the `brand_image` parameter in the `config.toml` file was not set.  Users don't have  to set a `brand_image` (in fact, it's commented out in the example `config.toml` file I provide), so that's definitely a bug.  

I believe I've fixed it now, so it should work regardless of whether a `brand_image` has been set.  Please try it out and let me know if it's working for you.  

Thanks again for pointing my attention to this!

**Comment by CodeF0x** [comment]
Hi @lukeorth, either I'm doing something wrong or the issue persists. Following the installation instruction of this repo and using the example config you provides in the readme, I get the following when running `hugo server`:

```
tobi@DESKTOP-37DTTQC ~/personal-website [255]> hugo server
Start building sites …
hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1
ERROR 2023/07/17 17:37:42 render of "taxonomy" failed: execute of template failed: template: _default/list.html:1:3: executing "_default/list.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:16:7: executing "partials/head/head.html" at <partial "head/meta.html" .>: error calling partial: "/home/tobi/personal-website/themes/poison/layouts/partials/head/meta.html:27:26": execute of template failed: template: partials/head/meta.html:27:26: executing "partials/head/meta.html" at <.Resources.Get>: can't evaluate field Get in type resource.Resources
ERROR 2023/07/17 17:37:42 render of "taxonomy" failed: execute of template failed: template: _default/list.html:1:3: executing "_default/list.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:16:7: executing "partials/head/head.html" at <partial "head/meta.html" .>: error calling partial: "/home/tobi/personal-website/themes/poison/layouts/partials/head/meta.html:27:26": execute of template failed: template: partials/head/meta.html:27:26: executing "partials/head/meta.html" at <.Resources.Get>: can't evaluate field Get in type resource.Resources
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:1:3: executing "index.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:16:7: executing "partials/head/head.html" at <partial "head/meta.html" .>: error calling partial: "/home/tobi/personal-website/themes/poison/layouts/partials/head/meta.html:27:26": execute of template failed: template: partials/head/meta.html:27:26: executing "partials/head/meta.html" at <.Resources.Get>: can't evaluate field Get in type resource.Resources
Built in 15 ms
```

Could you please have a look at it?

**Comment by lukeorth** [comment]
Hi @CodeF0x - I'm sorry to hear this is causing issues for you.  I performed the following steps and everything seems to be working on my end:

1. Create new Hugo site using `hugo new site` command
2. Clone the Poison theme into the themes directory using `git clone https://github.com/lukeorth/poison.git`
3. Enable the theme by copying the example `config.toml` from this repo's README

Just out of curiosity, which commit are you on?

**Comment by CodeF0x** [comment]
Thanks for helping me @lukeorth. 

I've tried again and the issue persists. 

`hugo version`  gives me:
```
hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1
```

poison's commit is `3af78e1d66989274603f7bef29abf9fc1c94c47c`

**Comment by lukeorth** [comment]
@CodeF0x, no worries!  I hadn't thought to check the Hugo version.  That's good to know, especially in case other people experience similar issues.

Thanks for reporting! :+1:
